### ISSUE TITLE
[DOC] Project documentation with .md files

### ISSUE THREAD

**Issue by syedalimohsinbukhari** [syedalimohsinbukhari/Solvers#15]
There's currently no documentation on the front page of the project.

# TODO
Add the front page documentation on
- [ ] What the project is,
- [ ] What modules it holds,
- [ ] What's the use case,
